/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#f4fff6",
          100: "#ebf4e3",
          200: "#ebf4e3",
          300: "#a6cbc2",
          400: "#b2ce6b ",
          500: "#a0bb5c",
          600: "#8ea84e",
          700: "#768d3b",
          800: "#4b8c62",
          900: "#17443e",
        },
        gray: {
          50: "#f4fff6",
          100: "#ebf4e3",
          200: "#ebf4e3",
          300: "#a6cbc2",
          400: "#b2ce6b ",
          500: "#a0bb5c",
          600: "#8ea84e",
          700: "#768d3b",
          800: "#4b8c62",
          900: "#17443e",
        },
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [require("flowbite/plugin")],
};
